### ISSUE TITLE
Attributes: display derived damage bonus from strength 

### ISSUE THREAD

**Issue by ulken** [Ganodorf/edrania-plugin#62]
I think the word on the street is every 10 strength point yields 1 damage bonus. Might be worth investigating a little further.

**Comment by Ganodorf** [comment]
I have noticed the same thing. Especially now after this season when I played a "strength only" troll. But yes a bit more testing would be nice.

**Comment by ulken** [comment]
I've seen plenty people state so and it also aligns with my own observations quite well. I'd say we assume so until someone tells us differently.
