### ISSUE TITLE
Work district: ensure not ending up on 0 rounds left

### ISSUE THREAD

**Issue by ulken** [Ganodorf/edrania-plugin#77]
- [x] Add setting to enable
- [x] Add setting to set default rounds
- [x] Pick the option lower than available rounds if otherwise ending up on 0 rounds.
- [x] Don't promote 10 rounds as that yields worse return. Show inline warning message instead.

**Comment by Ganodorf** [comment]
Might be a good idea to make this optional.

**Comment by ulken** [comment]
Maybe. Personally, I don't see how this differs from defaulting the **Workshop** rounds to available rounds - 1. The motivation is the same: prevent people from using up all their rounds by mistake, leaving them unable to fight.

If you feel strongly about it, I suggest we run a poll and ask people what they think. If not, I say we go and if people start complaining we adjust.

**Comment by ulken** [comment]
Ran a poll. You were right. Setting it is.
